#!/usr/bin/env bash
# TheNightOps — Kubernetes Manifest Generator
#
# Reads environment variables (from config/.env or shell) and renders
# deploy/gke/ templates into deploy/generated/ with real values substituted.
#
# Usage:
#   ./scripts/generate-manifests.sh
#
# Prerequisites:
#   - config/.env file with your values (copy from config/.env.example)
#   - OR set environment variables directly before running
#
# Optional:
#   IMAGE=us-central1-docker.pkg.dev/my-project/thenightops/nightops-agent:latest

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE_DIR="${PROJECT_ROOT}/deploy/gke"
OUTPUT_DIR="${PROJECT_ROOT}/deploy/generated"
ENV_FILE="${PROJECT_ROOT}/config/.env"

# ── Load config/.env if it exists ─────────────────────────────────
if [[ -f "${ENV_FILE}" ]]; then
    echo "→ Loading config from ${ENV_FILE}"
    set -a
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +a
else
    echo "⚠ No config/.env found — using environment variables only"
    echo "  (Copy config/.env.example to config/.env and fill in your values)"
fi

# ── Validate required variables ───────────────────────────────────
MISSING=()
[[ -z "${GOOGLE_API_KEY:-}" ]] && MISSING+=("GOOGLE_API_KEY")
[[ -z "${GCP_PROJECT_ID:-}" ]] && MISSING+=("GCP_PROJECT_ID")

if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo ""
    echo "✗ Missing required environment variables:"
    for var in "${MISSING[@]}"; do
        echo "    - ${var}"
    done
    echo ""
    echo "  Set them in config/.env or export before running."
    exit 1
fi

# ── Defaults ──────────────────────────────────────────────────────
GKE_CLUSTER_NAME="${GKE_CLUSTER_NAME:-nightops-demo}"
GKE_CLUSTER_LOCATION="${GKE_CLUSTER_LOCATION:-us-central1-a}"
REGION="${GCP_REGION:-us-central1}"

# Container images — default to Artifact Registry paths
IMAGE="${IMAGE:-${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/thenightops/nightops-agent:latest}"
DEMO_IMAGE="${DEMO_IMAGE:-${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/thenightops/nightops-demo-api:latest}"

# Optional secrets — default to empty
SLACK_BOT_TOKEN="${SLACK_BOT_TOKEN:-}"
GRAFANA_URL="${GRAFANA_URL:-http://grafana.monitoring:3000}"
GRAFANA_SERVICE_ACCOUNT_TOKEN="${GRAFANA_SERVICE_ACCOUNT_TOKEN:-}"
SMTP_HOST="${SMTP_HOST:-}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_USER="${SMTP_USER:-}"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"
FROM_EMAIL="${FROM_EMAIL:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"

SA_EMAIL="thenightops-agent@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

# ── Prepare output directory ──────────────────────────────────────
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

echo ""
echo "╔═══════════════════════════════════════════════════════╗"
echo "║     TheNightOps — Generating K8s Manifests            ║"
echo "╠═══════════════════════════════════════════════════════╣"
echo "║ Project:  ${GCP_PROJECT_ID}"
echo "║ Cluster:  ${GKE_CLUSTER_NAME}"
echo "║ Location: ${GKE_CLUSTER_LOCATION}"
echo "║ Agent:    ${IMAGE}"
echo "║ Demo:     ${DEMO_IMAGE}"
echo "║ Output:   deploy/generated/"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# ── 1. Namespace (no substitution needed) ─────────────────────────
echo "→ Generating namespace.yaml"
cp "${TEMPLATE_DIR}/namespace.yaml" "${OUTPUT_DIR}/namespace.yaml"
echo "  ✓ namespace.yaml"

# ── 2. ConfigMap (no substitution needed) ─────────────────────────
echo "→ Generating configmap.yaml"
cp "${TEMPLATE_DIR}/configmap.yaml" "${OUTPUT_DIR}/configmap.yaml"
echo "  ✓ configmap.yaml"

# ── 3. Secrets (render from env vars) ─────────────────────────────
echo "→ Generating secrets.yaml"
cat > "${OUTPUT_DIR}/secrets.yaml" <<EOF
# Auto-generated by scripts/generate-manifests.sh
# DO NOT commit this file to git.

apiVersion: v1
kind: Secret
metadata:
  name: nightops-secrets
  namespace: nightops
  labels:
    app.kubernetes.io/part-of: thenightops
type: Opaque
stringData:
  GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
  GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
  GKE_CLUSTER_NAME: "${GKE_CLUSTER_NAME}"
  GKE_CLUSTER_LOCATION: "${GKE_CLUSTER_LOCATION}"
  SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
  GRAFANA_URL: "${GRAFANA_URL}"
  GRAFANA_SERVICE_ACCOUNT_TOKEN: "${GRAFANA_SERVICE_ACCOUNT_TOKEN}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_USER: "${SMTP_USER}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  FROM_EMAIL: "${FROM_EMAIL}"
  TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
  TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
EOF
echo "  ✓ secrets.yaml (from env vars)"

# ── 4. Agent (substitute image + Workload Identity) ──────────────
echo "→ Generating agent.yaml"
sed -e "s|AGENT_IMAGE|${IMAGE}|g" \
    -e "s|# iam.gke.io/gcp-service-account:.*|iam.gke.io/gcp-service-account: ${SA_EMAIL}|g" \
    -e '/^    {}$/d' \
    "${TEMPLATE_DIR}/agent.yaml" > "${OUTPUT_DIR}/agent.yaml"
echo "  ✓ agent.yaml (image: ${IMAGE})"

# ── 5. MCP Servers (substitute image) ────────────────────────────
echo "→ Generating mcp-servers.yaml"
sed "s|AGENT_IMAGE|${IMAGE}|g" \
    "${TEMPLATE_DIR}/mcp-servers.yaml" > "${OUTPUT_DIR}/mcp-servers.yaml"
echo "  ✓ mcp-servers.yaml"

# ── 6. Dashboard (substitute image) ──────────────────────────────
echo "→ Generating dashboard.yaml"
sed "s|AGENT_IMAGE|${IMAGE}|g" \
    "${TEMPLATE_DIR}/dashboard.yaml" > "${OUTPUT_DIR}/dashboard.yaml"
echo "  ✓ dashboard.yaml"

# ── 7. Demo App (substitute demo image) ──────────────────────────
DEMO_TEMPLATE_DIR="${PROJECT_ROOT}/demo/k8s_manifests"
DEMO_OUTPUT_DIR="${OUTPUT_DIR}/demo"
mkdir -p "${DEMO_OUTPUT_DIR}"

echo "→ Generating demo app manifests"
sed "s|DEMO_IMAGE|${DEMO_IMAGE}|g" \
    "${DEMO_TEMPLATE_DIR}/demo-app.yaml" > "${DEMO_OUTPUT_DIR}/demo-app.yaml"
echo "  ✓ demo/demo-app.yaml"

sed "s|DEMO_IMAGE|${DEMO_IMAGE}|g" \
    "${DEMO_TEMPLATE_DIR}/memory-leak-scenario.yaml" > "${DEMO_OUTPUT_DIR}/memory-leak-scenario.yaml"
echo "  ✓ demo/memory-leak-scenario.yaml"

sed "s|DEMO_IMAGE|${DEMO_IMAGE}|g" \
    "${DEMO_TEMPLATE_DIR}/cpu-spike-scenario.yaml" > "${DEMO_OUTPUT_DIR}/cpu-spike-scenario.yaml"
echo "  ✓ demo/cpu-spike-scenario.yaml"

# ── Summary ───────────────────────────────────────────────────────
echo ""
echo "✓ All manifests generated in deploy/generated/"
echo ""
echo "To deploy agent:"
echo "  kubectl apply -f deploy/generated/"
echo ""
echo "To deploy demo app:"
echo "  kubectl apply -f deploy/generated/demo/demo-app.yaml"
echo ""
echo "To trigger a scenario:"
echo "  kubectl apply -f deploy/generated/demo/memory-leak-scenario.yaml"
echo ""
echo "To verify:"
echo "  kubectl get pods -n nightops"
echo "  kubectl get pods -n nightops-demo"
