"""
TheNightOps Interactive Setup Wizard.

Run after cloning the repo: `nightops init`
Walks the user through configuring all services, notification channels,
and validates connectivity before first use.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

from thenightops.core.logging import print_banner

console = Console()

# ── Wizard State ────────────────────────────────────────────────────


class WizardConfig:
    """Collects configuration during the wizard flow."""

    def __init__(self):
        # GCP
        self.gcp_project_id: str = ""
        self.gke_cluster_name: str = ""
        self.gke_cluster_location: str = ""
        self.google_api_key: str = ""

        # Notifications
        self.enable_slack: bool = False
        self.slack_bot_token: str = ""
        self.slack_incident_channel: str = "#incidents"

        self.enable_email: bool = False
        self.smtp_host: str = ""
        self.smtp_port: int = 587
        self.smtp_user: str = ""
        self.smtp_password: str = ""
        self.from_email: str = ""
        self.alert_emails: list[str] = []

        self.enable_telegram: bool = False
        self.telegram_bot_token: str = ""
        self.telegram_chat_id: str = ""

        self.enable_whatsapp: bool = False
        self.whatsapp_api_url: str = ""
        self.whatsapp_api_token: str = ""
        self.whatsapp_phone: str = ""

        # Agent
        self.model: str = "gemini-2.0-flash"

    def to_env(self) -> str:
        """Generate .env file content."""
        lines = [
            "# TheNightOps Configuration",
            "# Generated by: nightops init",
            "",
            "# ── Google Cloud Platform ──────────────────────────────────",
            f"GCP_PROJECT_ID={self.gcp_project_id}",
            f"GOOGLE_API_KEY={self.google_api_key}",
            "",
            "# ── GKE Cluster ───────────────────────────────────────────",
            f"GKE_CLUSTER_NAME={self.gke_cluster_name}",
            f"GKE_CLUSTER_LOCATION={self.gke_cluster_location}",
            "",
        ]

        if self.enable_slack:
            lines.extend([
                "# ── Slack ─────────────────────────────────────────────────",
                f"SLACK_BOT_TOKEN={self.slack_bot_token}",
                f"SLACK_INCIDENT_CHANNEL={self.slack_incident_channel}",
                "",
            ])

        if self.enable_email:
            lines.extend([
                "# ── Email (SMTP) ──────────────────────────────────────────",
                f"SMTP_HOST={self.smtp_host}",
                f"SMTP_PORT={self.smtp_port}",
                f"SMTP_USER={self.smtp_user}",
                f"SMTP_PASSWORD={self.smtp_password}",
                f"FROM_EMAIL={self.from_email}",
                f"ALERT_EMAILS={','.join(self.alert_emails)}",
                "",
            ])

        if self.enable_telegram:
            lines.extend([
                "# ── Telegram ──────────────────────────────────────────────",
                f"TELEGRAM_BOT_TOKEN={self.telegram_bot_token}",
                f"TELEGRAM_CHAT_ID={self.telegram_chat_id}",
                "",
            ])

        if self.enable_whatsapp:
            lines.extend([
                "# ── WhatsApp ──────────────────────────────────────────────",
                f"WHATSAPP_API_URL={self.whatsapp_api_url}",
                f"WHATSAPP_API_TOKEN={self.whatsapp_api_token}",
                f"WHATSAPP_PHONE_NUMBER={self.whatsapp_phone}",
                "",
            ])

        lines.extend([
            "# ── Agent ─────────────────────────────────────────────────",
            f"NIGHTOPS_MODEL={self.model}",
            "",
        ])

        return "\n".join(lines)


# ── Wizard Steps ────────────────────────────────────────────────────


def run_wizard() -> None:
    """Run the interactive setup wizard."""
    print_banner()
    console.print(
        Panel(
            "[bold]Welcome to TheNightOps Setup Wizard[/bold]\n\n"
            "This wizard will configure your environment step by step.\n"
            "You can skip any section by pressing Enter on required fields\n"
            "and configure them later in config/.env",
            style="cyan",
        )
    )

    config = WizardConfig()

    # Step 1: Google Cloud
    _step_gcp(config)

    # Step 2: Notification Channels
    _step_notifications(config)

    # Step 3: Agent Configuration
    _step_agent(config)

    # Step 4: Review & Save
    _step_review_and_save(config)

    # Step 5: Validate
    _step_validate(config)

    console.print("\n[bold green]Setup complete! TheNightOps is ready.[/bold green]\n")
    console.print("Next steps:")
    console.print("  1. [cyan]nightops verify[/cyan]         — Run full dependency check")
    console.print("  2. [cyan]nightops demo deploy[/cyan]    — Deploy demo app to GKE")
    console.print("  3. [cyan]nightops mcp start --all[/cyan] — Start custom MCP servers")
    console.print("  4. [cyan]nightops dashboard[/cyan]      — Open the investigation dashboard")
    console.print("  5. [cyan]nightops demo trigger -s memory-leak[/cyan] — Trigger a demo incident")
    console.print("  6. [cyan]nightops agent run --interactive[/cyan]    — Start investigation\n")


def _step_gcp(config: WizardConfig) -> None:
    """Configure Google Cloud Platform settings."""
    console.print("\n[bold cyan]Step 1/3: Google Cloud Platform[/bold cyan]")
    console.print("[dim]Required for official GKE and Cloud Observability MCP servers[/dim]\n")

    config.gcp_project_id = Prompt.ask(
        "  GCP Project ID",
        default=os.getenv("GCP_PROJECT_ID", ""),
    )

    config.gke_cluster_name = Prompt.ask(
        "  GKE Cluster name",
        default=os.getenv("GKE_CLUSTER_NAME", "nightops-demo"),
    )

    config.gke_cluster_location = Prompt.ask(
        "  GKE Cluster location (zone or region)",
        default=os.getenv("GKE_CLUSTER_LOCATION", "us-central1-a"),
    )

    config.google_api_key = Prompt.ask(
        "  Google AI API key (for Gemini/ADK)",
        default=os.getenv("GOOGLE_API_KEY", ""),
        password=True,
    )

    # Check if gcloud is authenticated
    try:
        result = subprocess.run(
            ["gcloud", "config", "get-value", "project"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            console.print(f"  [green]✓ gcloud authenticated (project: {result.stdout.strip()})[/green]")
        else:
            console.print("  [yellow]⚠ gcloud not configured. Run: gcloud auth login[/yellow]")
    except FileNotFoundError:
        console.print("  [yellow]⚠ gcloud CLI not found. Install: https://cloud.google.com/sdk[/yellow]")


def _step_notifications(config: WizardConfig) -> None:
    """Configure notification channels."""
    console.print("\n[bold cyan]Step 2/3: Notification Channels[/bold cyan]")
    console.print("[dim]Choose how TheNightOps alerts your team during incidents[/dim]\n")

    # Slack
    config.enable_slack = Confirm.ask("  Enable Slack notifications?", default=True)
    if config.enable_slack:
        config.slack_bot_token = Prompt.ask(
            "    Slack Bot Token (xoxb-...)",
            default=os.getenv("SLACK_BOT_TOKEN", ""),
            password=True,
        )
        config.slack_incident_channel = Prompt.ask(
            "    Incident channel",
            default="#incidents",
        )
        console.print("    [green]✓ Slack configured[/green]")

    # Email
    config.enable_email = Confirm.ask("  Enable Email (SMTP) notifications?", default=True)
    if config.enable_email:
        config.smtp_host = Prompt.ask("    SMTP host", default="smtp.gmail.com")
        config.smtp_port = int(Prompt.ask("    SMTP port", default="587"))
        config.smtp_user = Prompt.ask("    SMTP username/email")
        config.smtp_password = Prompt.ask("    SMTP password or app password", password=True)
        config.from_email = Prompt.ask(
            "    From email address",
            default=config.smtp_user,
        )
        alert_emails_str = Prompt.ask(
            "    Alert recipient emails (comma-separated)",
            default="",
        )
        config.alert_emails = [e.strip() for e in alert_emails_str.split(",") if e.strip()]
        console.print(f"    [green]✓ Email configured ({len(config.alert_emails)} recipients)[/green]")

    # Telegram
    config.enable_telegram = Confirm.ask("  Enable Telegram notifications?", default=False)
    if config.enable_telegram:
        config.telegram_bot_token = Prompt.ask("    Telegram Bot Token", password=True)
        config.telegram_chat_id = Prompt.ask("    Telegram Chat/Group ID")
        console.print("    [green]✓ Telegram configured[/green]")

    # WhatsApp
    config.enable_whatsapp = Confirm.ask("  Enable WhatsApp notifications?", default=False)
    if config.enable_whatsapp:
        config.whatsapp_api_url = Prompt.ask(
            "    WhatsApp Business API URL",
            default="https://graph.facebook.com/v17.0/YOUR_PHONE_NUMBER_ID",
        )
        config.whatsapp_api_token = Prompt.ask("    WhatsApp API Token", password=True)
        config.whatsapp_phone = Prompt.ask("    On-call phone number (+1234567890)")
        console.print("    [green]✓ WhatsApp configured[/green]")

    if not any([config.enable_slack, config.enable_email, config.enable_telegram, config.enable_whatsapp]):
        console.print("  [yellow]⚠ No notification channels configured. You can add them later in config/.env[/yellow]")


def _step_agent(config: WizardConfig) -> None:
    """Configure the AI agent."""
    console.print("\n[bold cyan]Step 3/3: Agent Configuration[/bold cyan]")
    console.print("[dim]Choose the Gemini model for investigation[/dim]\n")

    model_choice = Prompt.ask(
        "  Gemini model",
        choices=[
            "gemini-3.1-pro",
            "gemini-3-flash",
            "gemini-2.5-flash",
            "gemini-2.0-flash",
            "gemini-1.5-pro",
            "gemini-1.5-flash",
        ],
        default="gemini-2.5-flash",
    )
    config.model = model_choice
    console.print(f"    [green]✓ Using {model_choice}[/green]")


def _step_review_and_save(config: WizardConfig) -> None:
    """Review configuration and save to .env file."""
    console.print("\n[bold cyan]Configuration Summary[/bold cyan]\n")

    table = Table(show_header=True)
    table.add_column("Setting", style="cyan")
    table.add_column("Value")
    table.add_column("Status", style="bold")

    # GCP
    table.add_row("GCP Project", config.gcp_project_id or "(not set)", "[green]✓[/green]" if config.gcp_project_id else "[red]✗[/red]")
    table.add_row("GKE Cluster", f"{config.gke_cluster_name} ({config.gke_cluster_location})", "[green]✓[/green]" if config.gke_cluster_name else "[red]✗[/red]")
    table.add_row("Google AI Key", "****" if config.google_api_key else "(not set)", "[green]✓[/green]" if config.google_api_key else "[yellow]⚠[/yellow]")

    # MCP Servers (official)
    table.add_row("Cloud Observability MCP", "official (Google managed)", "[green]✓[/green]")
    table.add_row("GKE MCP", "official (Google managed)", "[green]✓[/green]")

    # Notifications
    table.add_row("Slack", "enabled" if config.enable_slack else "disabled", "[green]✓[/green]" if config.enable_slack else "[dim]—[/dim]")
    table.add_row("Email (SMTP)", f"enabled ({len(config.alert_emails)} recipients)" if config.enable_email else "disabled", "[green]✓[/green]" if config.enable_email else "[dim]—[/dim]")
    table.add_row("Telegram", "enabled" if config.enable_telegram else "disabled", "[green]✓[/green]" if config.enable_telegram else "[dim]—[/dim]")
    table.add_row("WhatsApp", "enabled" if config.enable_whatsapp else "disabled", "[green]✓[/green]" if config.enable_whatsapp else "[dim]—[/dim]")

    # Agent
    table.add_row("AI Model", config.model, "[green]✓[/green]")

    console.print(table)

    # Save
    if Confirm.ask("\n  Save this configuration?", default=True):
        env_path = Path("config/.env")
        env_path.parent.mkdir(parents=True, exist_ok=True)
        env_path.write_text(config.to_env())
        console.print(f"\n  [green]✓ Configuration saved to {env_path}[/green]")
    else:
        console.print("  [yellow]Configuration not saved. Run 'nightops init' again when ready.[/yellow]")


def _step_validate(config: WizardConfig) -> None:
    """Validate connectivity to configured services."""
    console.print("\n[bold cyan]Validating Configuration...[/bold cyan]\n")

    # Check GCP connectivity
    if config.gcp_project_id:
        try:
            result = subprocess.run(
                ["gcloud", "projects", "describe", config.gcp_project_id, "--format=value(projectId)"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                console.print(f"  [green]✓ GCP project '{config.gcp_project_id}' accessible[/green]")
            else:
                console.print(f"  [yellow]⚠ Cannot access GCP project: {result.stderr.strip()}[/yellow]")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            console.print("  [yellow]⚠ Cannot validate GCP (gcloud not available or timeout)[/yellow]")

    # Check if required APIs are enabled
    if config.gcp_project_id:
        for api in ["logging.googleapis.com", "container.googleapis.com"]:
            try:
                result = subprocess.run(
                    ["gcloud", "services", "list", "--enabled", f"--filter=name:{api}", "--format=value(name)", f"--project={config.gcp_project_id}"],
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                if api in result.stdout:
                    console.print(f"  [green]✓ API {api} enabled[/green]")
                else:
                    console.print(f"  [yellow]⚠ API {api} not enabled. Run: gcloud services enable {api}[/yellow]")
            except (FileNotFoundError, subprocess.TimeoutExpired):
                pass

    console.print("  [green]✓ Validation complete[/green]")


if __name__ == "__main__":
    run_wizard()
